export const BASE_API_URL = "http://localhost:5000";

export const Actions = {
  FETCH_ALL_IMAGES: "FETCH_ALL_IMAGES",
  UPLOAD_IMAGE: "UPLOAD_IMAGE",
  FETCH_ALL_MEMES: "FETCH_ALL_MEMES",
  UPLOAD_MEME: "UPLOAD_MEME",
  GET_ERRORS: "GET_ERRORS",
  CLEAR_ERRORS: "CLEAR_ERRORS",
};
